name: driver_app
description: RouteSync driver application.
publish_to: none
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../packages/core
  auth:
    path: ../../packages/auth
  deliveries:
    path: ../../packages/deliveries
  route:
    path: ../../packages/route
  provider: ^6.1.2
  go_router: ^14.6.2
  shared_preferences: ^2.3.5
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
